### PR TITLE
BF package pom: Add logback as optional dependency

### PR DESCRIPTION
**Pull request by dgault**
As a follow up to the issues discover with the bioformats_package ant tasks in https://github.com/ome/bioformats/pull/3942

### CODE REVIEW

**Review by sbesson — APPROVED** [review]
```
(java11) sbesson@Sebastiens-MacBook-Pro-2 bioformats % ant clean tools   
...
    [unzip] Expanding: /Users/sbesson/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.jar into /Users/sbesson/Documents/GitHub/bioformats/components/bundles/bioformats_package/build/unzip
    [unzip] Expanding: /Users/sbesson/.m2/repository/ch/qos/logback/logback-core/1.2.9/logback-core-1.2.9.jar into /Users/sbesson/Documents/GitHub/bioformats/components/bundles/bioformats_package/build/unzip
    [unzip] Expanding: /Users/sbesson/.m2/repository/ch/qos/logback/logback-classic/1.2.9/logback-classic-1.2.9.jar into /Users/sbesson/Documents/GitHub/bioformats/components/bundles/bioformats_package/build/unzip
      [jar] Building jar: /Users/sbesson/Documents/GitHub/bioformats/artifacts/bioformats_package.jar
   [delete] Deleting directory /Users/sbesson/Documents/GitHub/bioformats/components/bundles/bioformats_package/build/unzip
[resolver:install] Using default POM (ome:bioformats_package:6.12.0-SNAPSHOT)
[resolver:install] Installing /Users/sbesson/Documents/GitHub/bioformats/components/bundles/bioformats_package/pom.xml to /Users/sbesson/.m2/repository/ome/bioformats_package/6.12.0-SNAPSHOT/bioformats_package-6.12.0-SNAPSHOT.pom
[resolver:install] Installing /Users/sbesson/Documents/GitHub/bioformats/artifacts/bioformats_package.jar to /Users/sbesson/.m2/repository/ome/bioformats_package/6.12.0-SNAPSHOT/bioformats_package-6.12.0-SNAPSHOT.jar
[resolver:install] Installing ome:bioformats_package:6.12.0-SNAPSHOT/maven-metadata.xml to /Users/sbesson/.m2/repository/ome/bioformats_package/6.12.0-SNAPSHOT/maven-metadata-local.xml
[resolver:install] Installing ome:bioformats_package/maven-metadata.xml to /Users/sbesson/.m2/repository/ome/bioformats_package/maven-metadata-local.xml

BUILD SUCCESSFUL
Total time: 42 seconds
(java11) sbesson@Sebastiens-MacBook-Pro-2 bioformats % ./tools/showinf -nopix test.fake
Initializing reader
FakeReader initializing test.fake
Initialization took 0.054s

Reading core metadata
filename = test.fake
Used files = [/Users/sbesson/Documents/GitHub/bioformats/test.fake]
Series count = 1
Series #0 :
	Image count = 1
	RGB = false (1) 
	Interleaved = false
	Indexed = false (true color)
	Width = 512
	Height = 512
	SizeZ = 1
	SizeT = 1
	SizeC = 1
	Tile size = 512 x 512
	Thumbnail size = 128 x 128
	Endianness = intel (little)
	Dimension order = XYZCT (certain)
	Pixel type = uint8
	Valid bits per pixel = 8
	Metadata complete = true
	Thumbnail series = false
	-----
	Plane #0 <=> Z 0, C 0, T 0


Reading global metadata

Reading metadata
```

The logging dependencies are bundled with the uberJAR again and the functionality of the command-line tools are restored. I haven't tested the MATLAB/Octave toolbox which is the other known place which depends on the archive but the proposed change makes sense to me.

**Comment by sbesson** [comment]
>  Could the logback version be bumped to 1.3.5? see https://github.com/ome/bioformats/blob/develop/pom.xml#L43

See https://github.com/ome/bio-formats-examples/pull/102#issuecomment-1422904376, if we bump `logback` to 1.3.5. we might need to review `slf4j.version` as well.

**Comment by sbesson** [comment]
Based on the above, my proposal would be to:

- keep the Bio-Formats 6.12.x roadmap as defined re logback
- unify the versions in this repository to use `logback 1.2.x` to match the version of the upstream optional dependency
- review the documentation and indicate logging implementations must be explicitly declared but also note the slf4j version  declared in Bio-Formats and the compatibility implications with logback
- in upcoming minor versions, consider bumping `slf4j` to 2.0 (and bump logback to 1.3.x in this repository). This will probably need to happen across all components

Concerns, thoughts or alternate proposals welcome @ome/formats

**Comment by dgault** [comment]
Discussed with Jean-Marie and we are also in agreement on keeping the current versions for the 6.12.0 roadmap and potentially look at bumping both logback and slf4j in a future release. 

If there are no vetoes to that plan from the Glencoe side then I propose getting this merged and I will begin retesting the milestone release process first thing tomorrow.

**Review by melissalinkert — APPROVED** [review]

**Pull request merged**
