### PR TITLE
Bump imagej version to 1.54c

### PR DESCRIPTION
**Pull request by dgault**
Bumping the ImageJ version as per https://github.com/ome/bioformats/issues/3970
Required one small API addition

### CODE REVIEW

**Review by sbesson — COMMENTED** [review]
Looks good to me and aligns with the version declared in `pom-scijava`. Is there some specific workflow to test regarding the `getForegroundValue` API override?

**Review by melissalinkert — APPROVED** [review]
Looks good to me. `getForegroundValue` was introduced here: https://github.com/imagej/ImageJ/commit/9456cd28508ea44dbb5c750e25d9d33f766eb1e5#diff-775a1e8b431e15d67316903dd2511ce8ed7bdfdcc0466b7ffe5dacbf4313047d. I think the override makes sense and is consistent with how `RecordedImageProcessor` implements other methods.

**Comment by dgault** [comment]
@sbesson, I haven't found a nice way of testing `getForegroundValue` functionality through the GUI. Without the addition it will throw a compilation failure with the dependency bump so it is required to be there, but seems tricky to test. The API addition has actually been included with ImageJ1 for a while now and is included with the current version of FIJI available for download, so this has actually been missing in the `RecordedImageProcessor` for a while now. 

The best I could manage was through a small jython script, run in a fresh FIJI install.

The script is very basic, simply ensuring that the new API call returns as expected.

```
from loci.plugins.util import BFVirtualStack
from loci.formats import ImageReader
from loci.formats import MetadataTools
from ij.io import OpenDialog
 
od = OpenDialog("Choose image file", None)
file = od.getPath()
print "Reading file ", file
reader = ImageReader()
omeMeta = MetadataTools.createOMEXMLMetadata()
reader.setMetadataStore(omeMeta)
reader.setId(file)
bfvs = BFVirtualStack(file, reader, False, False, False)
proc = bfvs.getProcessor(1)
recProc = bfvs.getRecordedProcessor()
value = recProc.getForegroundValue()
reader.close()
print "Success, foreground value is ", value
```

Without this PR the script will not complete and you will receive the below error:

```
  File "Macro.ijm.py", line 16, in <module>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
java.lang.AbstractMethodError: java.lang.AbstractMethodError: loci.plugins.util.RecordedImageProcessor.getForegroundValue()D

	at org.python.core.Py.JavaError(Py.java:547)
	at org.python.core.Py.JavaError(Py.java:538)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:192)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:208)
```

With the PR (copying the bio-formats_plugins jar to the plugin folder) the script is able to complete without exception.

**Review by sbesson — APPROVED** [review]
Understood and thanks for the extra investigation @dgault. Let's get this merged for inclusion in 6.13.0

**Pull request merged**
