### PR TITLE
MetaMorph ND - Use version number to generate fileset

### PR DESCRIPTION
**Pull request by dgault**
This PR is follow up to a previously closed PR https://github.com/openmicroscopy/bioformats/pull/2860 and is in response to issue https://github.com/openmicroscopy/bioformats/issues/2613

I have been further investigating this issue today and main issue we really need to resolve is to be able to correctly identify from the .nd file if the associated files are .stk or .tif format. Taking a look at http://mdc.custhelp.com/app/answers/detail/a_id/18979/kw/nd provides a more up to date spec than the one we previously had been using. It does confirm that a mixture of both stk and tif is valid. It also states that .stk indicates a z series was performed and stored in a MetaMorph stack file.

The more relevant part is as follows:

```
1 The file type used for Z series data – Stack (*.stk) or the newer Meta Series Single/Multi-plane TIFF (*.tif) – is determined by the option Save Images Using Legacy Format (.stk, old-format .tif). 
To use this option, from the Edit menu, select Preferences > Image Save Preference. 
The .ND file records which file type is used:  NDInfoFile Version 1.0 – Legacy format or NDInfoFile Version 2.0 – newer Single/Multi-planeTIF format.
```

This would suggest that for Version 2.0 we have only `tif` files. While for Version 1.0 we can check each wavelength to see if the expected file is `.stk` or not using WaveDoZ2", TRUE.

This logic was used to update the fileset being used by looking specifically for an `stk` or `tif` rather than matching either. 

As the MetamorphReader extends BaseTiffReader the metadata was being initialised by first initialising a tif or stk before the nd was read. This now occurs after the `nd` has been parsed and the `stk` list generated. This does mean than adding the key value pairs from the `nd` must occur after the initialisation and as such there is some duplication in the parsing.

To test:
- Ensure all builds and tests remain green
- Test using the sample files from QA-17379
- Without the PR opening the nd file should result in the tiff being used (in FIJI for example this can be seen in the header bar). Also the white areas of the image should show some wrapping in pixel intensity (screenshot below shows the effect on the right hand side).
- Without the PR repeating the above step should result in the stk files should be read. There should be no wrapping in pixel intensity (screenshot below shows the correct image on the left hand side).

screen shot 2018-01-04 at 11 33 41

### CODE REVIEW

**Comment by sbesson** [comment]
From an initial execution of the automated tests aginst the [metamorph directory](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/530/console), it looks like 4f82118 breaks the `setId` on existing filesets. Marking this as `breaking` for now as it requires more investigation and to prevent false negatives in the daily integration jobs.

**Comment by dgault** [comment]
Failures appear to be due to no associated files being located for a given nd. Further investigation of the particular datasets required.

**Comment by imagejan** [comment]
Any news on this one yet?

**Comment by dgault** [comment]
@imagejan I will take a further look at the exceptions tomorrow to see if we can get everything passing this week

**Comment by sbesson** [comment]
@dgault the last push here seems to have affected the performance and non-regression tests against the metamorph files - see https://web-proxy.openmicroscopy.org/west-ci/job/BIOFORMATS-performance/32/ and https://web-proxy.openmicroscopy.org/west-ci/job/BIOFORMATS-test-folder/16636/console.

Given the late hour, I suggest we re-exclude this effort and try to get #3167 with the configured test for 5.9.0 and try to revisit this later.

**Comment by imagejan** [comment]
@sbesson which are the files the make the tests fail? Are the datasets available that you use for testing?
It's just that nowhere in the Metamorph specifcation I can see how unrelated files like in the dataset from https://github.com/openmicroscopy/bioformats/issues/2613 could ever belong to the same dataset: they clearly have a different base name.

In my understanding bio-formats at some stage looks at the _first_ occurrence of an underscore (`_`) to determine the basename - which is plain wrong and will fail if the basename itself contains underscores.

**Comment by sbesson** [comment]
@imagejan unfortunately, the files were originally sent to us privately and we do not have received permissions to make them public. We will contact the author separately and ask whether this could happen. At the same time, I am looking at other public samples to reproduce these failures.

To give at least some information, the failing case is a Z-stack fileset composed of 2 files: a .nd file and a .stk file. So the issue is very similar to https://github.com/openmicroscopy/bioformats/pull/3032#issuecomment-356060822 i.e. the reader fails to detect and associate the pixel STK files to the master ND files.

**Comment by imagejan** [comment]
What about this pull request? Can we work on getting it merged? I believe it would fix quite a few issues with the Metamorph format, and users keep running into issues with this, e.g. see https://gitter.im/imagej/imagej?at=5ff59e4e14cec811ec7fab20

**Comment by dgault** [comment]
Im going to reinclude this PR again for testing in the hope of getting this merged. Worst case scenario I may add an option flag to switch between the new and old behaviour.

**Review by sbesson — APPROVED** [review]
Tested the last set of commits with the representative fileset uploaded as part of https://github.com/ome/bioformats/issues/2613. Without this PR, the command-line tools shows the detection issue as the `getUsedFiles` API returns the correct constituent of the fileset but `getCurrentFile` returns a completely separate file:

```
sbesson@ls30630:Downloads $ ./bftools-6.6.0/showinf ~/Desktop/nd_issue/ScanSlide_exp1_rep1.nd 
Checking file format [Metamorph STK]
Initializing reader
MetamorphReader initializing /Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1.nd
Initializing /Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1.nd
Looking for STK file in /Users/sbesson/Desktop/nd_issue
Reading IFDs
Populating metadata
Populating OME metadata
Initialization took 0.126s

Reading core metadata
filename = /Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep0_w1confGFP_s1.tif
Used files:
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1.nd
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w1confGFP_s1.STK
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w2confDAPI_s1.STK
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w1confGFP_s2.STK
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w2confDAPI_s2.STK
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w1confGFP_s3.STK
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w2confDAPI_s3.STK
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w1confGFP_s4.STK
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w2confDAPI_s4.STK
```

Both the display from the command-line utility and Fiji/Image look incorrect with the title bar pointing to `ScanSlide_exp1_rep0_w1confGFP_s1.tif`, the thumbnails being rendered as white and the pixels displaying incorrectly. Since OMERO only transfers the files returned by `getUsedFiles`, this bug could not be reproduced using this workflow.

Screenshot 2021-03-15 at 15 03 24
Screenshot 2021-03-15 at 15 03 28
Screenshot 2021-03-15 at 15 03 02

With this PR included, both the returned current file as well as the used files match the expectations:

```
sbesson@ls30630:Downloads $ ./bftools/showinf ~/Desktop/nd_issue/ScanSlide_exp1_rep1.nd 
Checking file format [Metamorph STK]
Initializing reader
MetamorphReader initializing /Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1.nd
Initializing /Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1.nd
Looking for STK file in /Users/sbesson/Desktop/nd_issue
Reading IFDs
Populating metadata
Populating OME metadata
Initialization took 0.118s

Reading core metadata
filename = /Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w1confGFP_s1.stk
Used files:
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1.nd
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w1confGFP_s1.STK
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w2confDAPI_s1.STK
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w1confGFP_s2.STK
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w2confDAPI_s2.STK
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w1confGFP_s3.STK
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w2confDAPI_s3.STK
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w1confGFP_s4.STK
	/Users/sbesson/Desktop/nd_issue/ScanSlide_exp1_rep1_w2confDAPI_s4.STK
```

In terms of rendering, the command-line tools and ImageJ/Fiji display thumbnails and pixel data as expected:

Screenshot 2021-03-15 at 15 03 07
Screenshot 2021-03-15 at 16 13 08
Screenshot 2021-03-15 at 16 13 18

In addition to the above, the content of the metadata is significantly improved with `Pixels.PhysicalSize`, `Channel.EmissionWavelength`, `Plane.Position`, `Plane.ExposureTime` being now being properly populated.

From a functional point of view, this PR fixes a long-standing issue associated with the detection of multiple Metamorph filesets under the same folder. We should configure a representative fileset and add it to the curated QA repository for non-regression but otherwise, I'd vote to get this merged. @imagejan once this fix gets deployed onto the Bio-Formats development update site, would youhave some capacity to confirm the last SNAPSHOT addresses the bug and improves your workflow?

One question from my side is whether `getCurrentFile` should return the `.nd` file rather than an arbitrary `.stk/.tif` file from the fileset. On the other side, this might break some workflow relying on the contract of `getCurrentFile` / the title of the ImageJ window so it might be more appropriate for a minor/major release.

**Comment by imagejan** [comment]
@sbesson wrote:
> would youhave some capacity to confirm the last SNAPSHOT addresses the bug and improves your workflow?

Sure, I'll be happy to test on our side!

**Comment by sbesson** [comment]
@imagejan that should be the latest SNAPSHOT build from https://github.com/ome/bioformats/commit/442c35a834a8b4a1e67925d9243bdf631e8628c8 now deployed onto the [development Bio-Formats update site](https://sites.imagej.net/Bio-Formats/). Also, we are currently projecting to release Bio-Formats 6.6.1 including this fix next week.
We will definitely welcome feedback from your side on whether this addresses the Metamorph issue (and we really hope it does 😃 ) if you have some capacity this week.

**Comment by imagejan** [comment]
Thanks a lot, @sbesson!

I can confirm that the most annoying issue &mdash; the reading of *metadata* from unrelated files &mdash; seems to be fixed. Datasets that were previously read with a wrong pixel spacing (when other datasets in the same folder differed in that metadata info) are now being read with the correct metadata when using the `6.6.1-SNAPSHOT` from the update site.

However, as my tests in https://github.com/fmi-basel/faim-imagej-bio-formats-tests/pull/1 show, there are still some remaining issues (compare running `mvn test` on [`98fd027`](https://github.com/fmi-basel/faim-imagej-bio-formats-tests/commits/98fd02749fe5ddaf1674c1587a53471653d5836c) (before) vs. ... (after)).

Most importantly, the image titles are still *not* the same when comparing a dataset being opened from an isolated folder, with the *same* dataset opened from a folder that contains other datasets (see errors listed below, in particular the `testEqualTitles` output, which has improved but is still different).

### Without the changes of this PR

<details>
<summary>Detailed test errors</summary>

```
[ERROR] Tests run: 36, Failures: 12, Errors: 0, Skipped: 0, Time elapsed: 37.903 s <<< FAILURE! - in ch.fmi.VisiViewFormatTest
[ERROR] testChannelNotInTitle[benchmark_v1_2018_x64y64z1c2s1t11](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.759 s  <<< FAILURE!
java.lang.AssertionError: Channel identifier in title of multi-channel image
        at ch.fmi.VisiViewFormatTest.testChannelNotInTitle(VisiViewFormatTest.java:123)

[ERROR] testEqualTitles[benchmark_v1_2018_x64y64z1c2s1t11](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.755 s  <<< FAILURE!
org.junit.ComparisonFailure: Image titles expected:<...rk_v1_2018_x64y64z1c[2s1t11_w1Laser4054BD4BP].tif> but was:<...rk_v1_2018_x64y64z1c[1s1t1].tif>
        at ch.fmi.VisiViewFormatTest.testEqualTitles(VisiViewFormatTest.java:108)

[ERROR] testOpenSingleDataset[benchmark_v1_2018_x64y64z1c2s4t11](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.385 s  <<< FAILURE!
java.lang.AssertionError: Read image (single dataset)
        at ch.fmi.VisiViewFormatTest.testOpenSingleDataset(VisiViewFormatTest.java:89)

[ERROR] testOpenWithOthersInFolder[benchmark_v1_2018_x64y64z1c2s4t11](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.384 s  <<< FAILURE!
java.lang.AssertionError: Read image (from folder with other datasets)
        at ch.fmi.VisiViewFormatTest.testOpenWithOthersInFolder(VisiViewFormatTest.java:94)

[ERROR] testOpenSingleDataset[benchmark_v1_2018_x64y64z1c2s4t12](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.395 s  <<< FAILURE!
java.lang.AssertionError: Read image (single dataset)
        at ch.fmi.VisiViewFormatTest.testOpenSingleDataset(VisiViewFormatTest.java:89)

[ERROR] testOpenWithOthersInFolder[benchmark_v1_2018_x64y64z1c2s4t12](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.395 s  <<< FAILURE!
java.lang.AssertionError: Read image (from folder with other datasets)
        at ch.fmi.VisiViewFormatTest.testOpenWithOthersInFolder(VisiViewFormatTest.java:94)

[ERROR] testChannelNotInTitle[benchmark_v1_2018_x64y64z5c2s1t11](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.669 s  <<< FAILURE!
java.lang.AssertionError: Channel identifier in title of multi-channel image
        at ch.fmi.VisiViewFormatTest.testChannelNotInTitle(VisiViewFormatTest.java:123)

[ERROR] testEqualTitles[benchmark_v1_2018_x64y64z5c2s1t11](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.67 s  <<< FAILURE!
org.junit.ComparisonFailure: Image titles expected:<...mark_v1_2018_x64y64z[5c2s1t11_w1Laser4054BD4BP.stk]> but was:<...mark_v1_2018_x64y64z[1c1s1t1.tif]>
        at ch.fmi.VisiViewFormatTest.testEqualTitles(VisiViewFormatTest.java:108)

[ERROR] testChannelNotInTitle[benchmark_v1_2018_x64y64z5c2s1t41](ch.fmi.VisiViewFormatTest)  Time elapsed: 1.693 s  <<< FAILURE!
java.lang.AssertionError: Channel identifier in title of multi-channel image
        at ch.fmi.VisiViewFormatTest.testChannelNotInTitle(VisiViewFormatTest.java:123)

[ERROR] testEqualTitles[benchmark_v1_2018_x64y64z5c2s1t41](ch.fmi.VisiViewFormatTest)  Time elapsed: 1.707 s  <<< FAILURE!
org.junit.ComparisonFailure: Image titles expected:<...mark_v1_2018_x64y64z[5c2s1t41_w1Laser4054BD4BP_t1.stk]> but was:<...mark_v1_2018_x64y64z[1c1s1t1.tif]>
        at ch.fmi.VisiViewFormatTest.testEqualTitles(VisiViewFormatTest.java:108)

[ERROR] testChannelNotInTitle[benchmark_v1_2018_x64y64z5c2s4t41](ch.fmi.VisiViewFormatTest)  Time elapsed: 1.709 s  <<< FAILURE!
java.lang.AssertionError: Channel identifier in title of multi-channel image
        at ch.fmi.VisiViewFormatTest.testChannelNotInTitle(VisiViewFormatTest.java:123)

[ERROR] testEqualTitles[benchmark_v1_2018_x64y64z5c2s4t41](ch.fmi.VisiViewFormatTest)  Time elapsed: 1.71 s  <<< FAILURE!
org.junit.ComparisonFailure: Image titles expected:<...mark_v1_2018_x64y64z[5c2s4t41_w1Laser4054BD4BP_s1_t1.stk] - Stage1 "Row0_Col0...> but was:<...mark_v1_2018_x64y64z[1c1s1t1.tif] - Stage1 "Row0_Col0...>
        at ch.fmi.VisiViewFormatTest.testEqualTitles(VisiViewFormatTest.java:108)
```
</details>

```
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   VisiViewFormatTest.testChannelNotInTitle:123 Channel identifier in title of multi-channel image
[ERROR]   VisiViewFormatTest.testChannelNotInTitle:123 Channel identifier in title of multi-channel image
[ERROR]   VisiViewFormatTest.testChannelNotInTitle:123 Channel identifier in title of multi-channel image
[ERROR]   VisiViewFormatTest.testChannelNotInTitle:123 Channel identifier in title of multi-channel image
[ERROR]   VisiViewFormatTest.testEqualTitles:108 Image titles expected:<...rk_v1_2018_x64y64z1c[2s1t11_w1Laser4054BD4BP].tif> but was:<...rk_v1_2018_x64y64z1c[1s1t1].tif>
[ERROR]   VisiViewFormatTest.testEqualTitles:108 Image titles expected:<...mark_v1_2018_x64y64z[5c2s1t11_w1Laser4054BD4BP.stk]> but was:<...mark_v1_2018_x64y64z[1c1s1t1.tif]>
[ERROR]   VisiViewFormatTest.testEqualTitles:108 Image titles expected:<...mark_v1_2018_x64y64z[5c2s1t41_w1Laser4054BD4BP_t1.stk]> but was:<...mark_v1_2018_x64y64z[1c1s1t1.tif]>
[ERROR]   VisiViewFormatTest.testEqualTitles:108 Image titles expected:<...mark_v1_2018_x64y64z[5c2s4t41_w1Laser4054BD4BP_s1_t1.stk] - Stage1 "Row0_Col0...> but was:<...mark_v1_2018_x64y64z[1c1s1t1.tif] - Stage1 "Row0_Col0...>
[ERROR]   VisiViewFormatTest.testOpenSingleDataset:89 Read image (single dataset)
[ERROR]   VisiViewFormatTest.testOpenSingleDataset:89 Read image (single dataset)
[ERROR]   VisiViewFormatTest.testOpenWithOthersInFolder:94 Read image (from folder with other datasets)
[ERROR]   VisiViewFormatTest.testOpenWithOthersInFolder:94 Read image (from folder with other datasets)
[INFO]
[ERROR] Tests run: 36, Failures: 12, Errors: 0, Skipped: 0
```

### With the changes of this PR

<details>
<summary>Detailed test errors</summary>

```
[ERROR] Tests run: 36, Failures: 12, Errors: 0, Skipped: 0, Time elapsed: 35.768 s <<< FAILURE! - in ch.fmi.VisiViewFormatTest
[ERROR] testChannelNotInTitle[benchmark_v1_2018_x64y64z1c2s1t11](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.764 s  <<< FAILURE!
java.lang.AssertionError: Channel identifier in title of multi-channel image
        at ch.fmi.VisiViewFormatTest.testChannelNotInTitle(VisiViewFormatTest.java:123)

[ERROR] testEqualTitles[benchmark_v1_2018_x64y64z1c2s1t11](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.762 s  <<< FAILURE!
org.junit.ComparisonFailure: Image titles expected:<...rk_v1_2018_x64y64z1c[2s1t11_w1Laser4054BD4BP].tif> but was:<...rk_v1_2018_x64y64z1c[1s1t1].tif>
        at ch.fmi.VisiViewFormatTest.testEqualTitles(VisiViewFormatTest.java:108)

[ERROR] testOpenSingleDataset[benchmark_v1_2018_x64y64z1c2s4t11](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.258 s  <<< FAILURE!
java.lang.AssertionError: Read image (single dataset)
        at ch.fmi.VisiViewFormatTest.testOpenSingleDataset(VisiViewFormatTest.java:89)

[ERROR] testOpenWithOthersInFolder[benchmark_v1_2018_x64y64z1c2s4t11](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.255 s  <<< FAILURE!
java.lang.AssertionError: Read image (from folder with other datasets)
        at ch.fmi.VisiViewFormatTest.testOpenWithOthersInFolder(VisiViewFormatTest.java:94)

[ERROR] testOpenSingleDataset[benchmark_v1_2018_x64y64z1c2s4t12](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.258 s  <<< FAILURE!
java.lang.AssertionError: Read image (single dataset)
        at ch.fmi.VisiViewFormatTest.testOpenSingleDataset(VisiViewFormatTest.java:89)

[ERROR] testOpenWithOthersInFolder[benchmark_v1_2018_x64y64z1c2s4t12](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.262 s  <<< FAILURE!
java.lang.AssertionError: Read image (from folder with other datasets)
        at ch.fmi.VisiViewFormatTest.testOpenWithOthersInFolder(VisiViewFormatTest.java:94)

[ERROR] testChannelNotInTitle[benchmark_v1_2018_x64y64z5c2s1t11](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.539 s  <<< FAILURE!
java.lang.AssertionError: Channel identifier in title of multi-channel image
        at ch.fmi.VisiViewFormatTest.testChannelNotInTitle(VisiViewFormatTest.java:123)

[ERROR] testEqualTitles[benchmark_v1_2018_x64y64z5c2s1t11](ch.fmi.VisiViewFormatTest)  Time elapsed: 0.533 s  <<< FAILURE!
org.junit.ComparisonFailure: Image titles expected:<...mark_v1_2018_x64y64z[5c2s1]t11_w1Laser4054BD4BP...> but was:<...mark_v1_2018_x64y64z[1c2s4]t11_w1Laser4054BD4BP...>
        at ch.fmi.VisiViewFormatTest.testEqualTitles(VisiViewFormatTest.java:108)

[ERROR] testChannelNotInTitle[benchmark_v1_2018_x64y64z5c2s1t41](ch.fmi.VisiViewFormatTest)  Time elapsed: 1.555 s  <<< FAILURE!
java.lang.AssertionError: Channel identifier in title of multi-channel image
        at ch.fmi.VisiViewFormatTest.testChannelNotInTitle(VisiViewFormatTest.java:123)

[ERROR] testEqualTitles[benchmark_v1_2018_x64y64z5c2s1t41](ch.fmi.VisiViewFormatTest)  Time elapsed: 1.552 s  <<< FAILURE!
org.junit.ComparisonFailure: Image titles expected:<...mark_v1_2018_x64y64z[5c2s1t41_w1Laser4054BD4BP_t1].stk> but was:<...mark_v1_2018_x64y64z[1c2s4t11_w1Laser4054BD4BP].stk>
        at ch.fmi.VisiViewFormatTest.testEqualTitles(VisiViewFormatTest.java:108)

[ERROR] testChannelNotInTitle[benchmark_v1_2018_x64y64z5c2s4t41](ch.fmi.VisiViewFormatTest)  Time elapsed: 1.56 s  <<< FAILURE!
java.lang.AssertionError: Channel identifier in title of multi-channel image
        at ch.fmi.VisiViewFormatTest.testChannelNotInTitle(VisiViewFormatTest.java:123)

[ERROR] testEqualTitles[benchmark_v1_2018_x64y64z5c2s4t41](ch.fmi.VisiViewFormatTest)  Time elapsed: 1.559 s  <<< FAILURE!
org.junit.ComparisonFailure: Image titles expected:<...mark_v1_2018_x64y64z[5c2s4t41_w1Laser4054BD4BP_s1_t1].stk - Stage1 "Row0_...> but was:<...mark_v1_2018_x64y64z[1c2s4t11_w1Laser4054BD4BP].stk - Stage1 "Row0_...>
        at ch.fmi.VisiViewFormatTest.testEqualTitles(VisiViewFormatTest.java:108)
```
</details>

```
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   VisiViewFormatTest.testChannelNotInTitle:123 Channel identifier in title of multi-channel image
[ERROR]   VisiViewFormatTest.testChannelNotInTitle:123 Channel identifier in title of multi-channel image
[ERROR]   VisiViewFormatTest.testChannelNotInTitle:123 Channel identifier in title of multi-channel image
[ERROR]   VisiViewFormatTest.testChannelNotInTitle:123 Channel identifier in title of multi-channel image
[ERROR]   VisiViewFormatTest.testEqualTitles:108 Image titles expected:<...rk_v1_2018_x64y64z1c[2s1t11_w1Laser4054BD4BP].tif> but was:<...rk_v1_2018_x64y64z1c[1s1t1].tif>
[ERROR]   VisiViewFormatTest.testEqualTitles:108 Image titles expected:<...mark_v1_2018_x64y64z[5c2s1]t11_w1Laser4054BD4BP...> but was:<...mark_v1_2018_x64y64z[1c2s4]t11_w1Laser4054BD4BP...>
[ERROR]   VisiViewFormatTest.testEqualTitles:108 Image titles expected:<...mark_v1_2018_x64y64z[5c2s1t41_w1Laser4054BD4BP_t1].stk> but was:<...mark_v1_2018_x64y64z[1c2s4t11_w1Laser4054BD4BP].stk>
[ERROR]   VisiViewFormatTest.testEqualTitles:108 Image titles expected:<...mark_v1_2018_x64y64z[5c2s4t41_w1Laser4054BD4BP_s1_t1].stk - Stage1 "Row0_...> but was:<...mark_v1_2018_x64y64z[1c2s4t11_w1Laser4054BD4BP].stk - Stage1 "Row0_...>
[ERROR]   VisiViewFormatTest.testOpenSingleDataset:89 Read image (single dataset)
[ERROR]   VisiViewFormatTest.testOpenSingleDataset:89 Read image (single dataset)
[ERROR]   VisiViewFormatTest.testOpenWithOthersInFolder:94 Read image (from folder with other datasets)
[ERROR]   VisiViewFormatTest.testOpenWithOthersInFolder:94 Read image (from folder with other datasets)
[INFO]
[ERROR] Tests run: 36, Failures: 12, Errors: 0, Skipped: 0
```

---

In addition, I see the following stack trace appearing in the log, related to parsing the timestamp:

```
17:30:22.781 [main] DEBUG loci.formats.FormatHandler - MetamorphReader initializing W:\groups\gmicro\eglijan\code\fmi-basel\faim-imagej-bio-formats-tests\target\test-classes\ch\fmi\benchmark_v1_2018_x64y64z5c2s4t41\benchmark_v1_2018_x64y64z5c2s4t41_w2Laser4914BD4BP_s1_t4.STK
17:30:22.782 [main] DEBUG loci.common.DateTools - Invalid timestamp '2018-08-24T13:05:58.712' for current locale
17:30:22.782 [main] DEBUG loci.common.DateTools - Could not parse timestamp '2018-08-24T13:05:58.712' with EN_US locale
java.lang.IllegalArgumentException: Invalid format: "2018-08-24T13:05:58.712" is malformed at ".712"
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945)
        at org.joda.time.Instant.parse(Instant.java:126)
        at loci.common.DateTools.parseDate(DateTools.java:291)
        at loci.common.DateTools.getTime(DateTools.java:461)
        at loci.common.DateTools.getTime(DateTools.java:447)
        at loci.plugins.in.ImagePlusReader.constructSliceLabel(ImagePlusReader.java:664)
        at loci.plugins.in.ImagePlusReader.readPlanes(ImagePlusReader.java:392)
        at loci.plugins.in.ImagePlusReader.readImage(ImagePlusReader.java:282)
        at loci.plugins.in.ImagePlusReader.readImages(ImagePlusReader.java:243)
        at loci.plugins.in.ImagePlusReader.readImages(ImagePlusReader.java:221)
        at loci.plugins.in.ImagePlusReader.openImagePlus(ImagePlusReader.java:116)
        at loci.plugins.BF.openImagePlus(BF.java:98)
        at loci.plugins.BF.openImagePlus(BF.java:77)
        at ch.fmi.VisiViewFormatTest.loadImages(VisiViewFormatTest.java:79)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

As I said, all of these remaining issue have been there before, and nothing was broken *because* of the current PR. So I'll be happy if the changes of this pull request make it to the release next week in any case 🙂 

Let me know if I should do further testing, or you need more details.

**Pull request merged**
