### PR TITLE
Improves performance of OperettaReader

### PR DESCRIPTION
**Pull request by NicoKiaru**
* Avoids a N^2 algorithm by using a hashmap to find the correct plane
* Very significant speedup for big dataset (k.100 000 planes), from 30 minutes to 30s with a 800 Mb xml file

### CODE REVIEW

**Comment by NicoKiaru** [comment]
Ping @dgault @sbesson 
See also https://github.com/ome/bioformats/pull/3770

**Comment by dgault** [comment]
Thanks @NicoKiaru, I have marked this for inclusion with the overnight builds and repo tests. We will aim to get this tested and reviewed within the coming days for inclusion in the next 6.9.0 release.

**Comment by dgault** [comment]
Also, we have recently introduced a CLA for contributors, would you be able to sign and return the form following the instructions on https://ome-contributing.readthedocs.io/en/latest/cla.html

**Comment by dgault** [comment]
All builds and tests have remained green with this PR included. The changes here look good and make perfect sense, removing the inner loop should greatly speed up large datasets with a large number of planes. The performance of the repo tests has also remained consistent (slightly improved), though we don't have extremely large xml samples included. Testing with the original sample that prompted the PR shows a great improvement from close to 30 mins down to < 30 secs.

Overall the PR looks good, once we receive the signed CLA it will be ready to merge.

**Comment by NicoKiaru** [comment]
I am trying to get some official approval from EPFL regarding the CLA. I do not expect any problem, especially regarding this minor code modification, but I hope to get an answer soon.... When do you plan to release 6.9.0 ?

**Comment by dgault** [comment]
We had hoped to be able to do the 6.9.0 release early next week

**Comment by NicoKiaru** [comment]
> I am trying to get some official approval from EPFL regarding the CLA. I do not expect any problem, especially regarding this minor code modification, but I hope to get an answer soon.... When do you plan to release 6.9.0 ?

Still no answers... I'm trying other channels of communication.

**Comment by dgault** [comment]
Thanks for the update @NicoKiaru

**Comment by NicoKiaru** [comment]
CLA sent!

**Comment by dgault** [comment]
Thanks, lets get this PR merged!

**Pull request merged**
