### PR TITLE
Added support for ColumbusReader to import data with z stacks

### LINKED ISSUE #3791: Add support for multi-Z images exported from Perkin Elmer Columbus
See https://forum.image.sc/t/bio-formats-doesnt-open-columbus-xml-file-properly-with-z-stack/43659 and https://forum.image.sc/t/import-of-old-operetta-images-bioformats-incompatibility/64139
 
A new format reader for the export data generated by PerkinElmer Columbus systems was introduced in https://github.com/ome/bioformats/pull/2830 and released since Bio-Formats 5.5.0.
This implementation reader was primarily driven by two IDR submissions (`idr0119` and `idr0120`) and reads multi-channel fields of views. As noted on the public threads above, fields of views with multiple Z planes (i.e. `sizeZ > 1`) are currently not supported.

Looking briefly at https://zenodo.org/record/6327496, a starting point might be to look at the `PlaneID` metadata  in the proprietary XML. Some  investigation had been started in https://github.com/ome/bioformats/pull/3193 but did not reach the maturity required to pass the Bio-Formats Q&A process.

### PR DESCRIPTION
**Pull request by TBlackmore**
Following up on issue #3791
I had the same problem importing data exported from PerkinElmer (Revvity) Columbus into Omero. No Z stacks were coming through. I've ammended the ColumbusReader and run some tests.
I have some test data I can provide, but I'm having an issue getting into Zenodo at the moment.

### CODE REVIEW

**Comment by dgault** [comment]
Thanks @TBlackmore for opening the PR, if are able to provide some sample files that would greatly help the testing. 

Also, we have a Contributor License Agreement for the project, would you be able to sign and return the form following the instructions on https://ome-contributing.readthedocs.io/en/latest/cla.html

**Comment by TBlackmore** [comment]
No worries @dgault :-) Happy to be helping!

I've uploaded a two test datasets [here](https://zenodo.org/records/10627948?token=eyJhbGciOiJIUzUxMiJ9.eyJpZCI6IjE4N2JkOTc3LWQxMTAtNDJlOC1iOTRmLTg2YmM5ZDQ3MzE0YyIsImRhdGEiOnt9LCJyYW5kb20iOiI4NDFhOWIyNGU2MTIzMThlMzc4MzFiNTc4NTgwOTUzNCJ9.4G0_VUqzT02fFsdlYrmMSHOiKzeeDluYlj6KlVWWcp25900USKU2HGte1to4MLXHnSRwfmeHzlEcJ5HH4UdLmg). One with single plane tifs, and one with multiplane.

I've also submitted the license agreement.

Let me know if there's anything else I can do to get this PR done.

**Comment by dgault** [comment]
Thanks @TBlackmore, having the samples to test with is a great help, we will aim to get this PR reviewed within the next week and let you know if there are any changes or updates required.

**Review by melissalinkert — COMMENTED** [review]
Only thing that might be worth reconsidering is the units on the plane positions. Based on the `ImageIndex.ColumbusIDX.xml` files, those values appear to be stored in meters, in which case `UNITS.METER` would be more suitable than `UNITS.REFERENCEFRAME`.

Otherwise, this looks fine to me once we have passing tests that include the new samples.

**Review by dgault — APPROVED** [review]
Testing manually with the new samples from the associated config PR and with these changes all of the files were able to be opened and displayed as expected with the correct Z stacks. The code changes look good to me and all tests have been green with the new sample files. As discussed with Melissa at the formats meeting, the comment about the units can be addressed in a follow up PR at a later date.

**Pull request merged**
