### PR TITLE
bug fix, thumb nails are unsigned integers, and exceeded 2^31, so I changed their size to Long

### PR DESCRIPTION
**Pull request by nicolapapp**
There were some large numbers (> 2^31) in the yaml metadata files which referred to the older sld format pointers in the file, and are not used in format 7 (sldy). These numbers anyway were read in as Integer and that generated an exception. I have tracked down several and changed them to Long. I have also added try/catch around the decoding of numbers from the yaml file, and that will produce warnings but will not kill the file load. If during testing you get any warnings in the console, please send them to me.

### CODE REVIEW

**Comment by nicolapapp** [comment]
There were some large numbers (> 2^31) in the yaml metadata files which referred to the older sld format pointers in the file, and are not used in format 7 (sldy). These numbers anyway were read in as Integer and that generated an exception. I have tracked down several and changed them to Long. I have also added try/catch around the decoding of numbers from the yaml file, and that will produce warnings but will not kill the file load. If during testing you get any warnings in the console, please send them to me.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by dgault** [comment]
@nicolapapp This PR seems to have caused some failures in our nightly repository tests, https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-test-folder/lastFailedBuild/console

It looks as though some files are now failing isThisType and not being recognised by the reader, and for others the physical pixel size seems to have changed:

  ```
 [testng] [2023-10-09 01:41:29,317] [pool-1-thread-1] 	PhysicalSizeX: FAILED (Series 0 (expected ome.units.quantity.Length: value[1.0], unit[µm] stored as java.lang.Double, actual ome.units.quantity.Length: value[0.10599999874830246], unit[µm] stored as java.lang.Double))
   [testng] [2023-10-09 01:41:29,318] [pool-1-thread-1] 	PhysicalSizeY: FAILED (Series 0 (expected ome.units.quantity.Length: value[1.0],
```

**Comment by dgault** [comment]
@nicolapapp, there is a large number of code changes included here that seem to be greater than the original description of the PR (changing unsigned ints to long). Are all of these changes meant to be included? Do you have a description of what other functionality has changed and how we can best test it?

**Comment by melissalinkert** [comment]
@nicolapapp : in order to consider this pull request for inclusion, we will need answers to the questions in https://github.com/ome/bioformats/pull/4100#issuecomment-1812733507. If we don't hear back from you within the next week, this pull request will be closed (but you are welcome to re-open it once the outstanding questions are answered).

**Comment by nicolapapp** [comment]
There were some large numbers (> 2^31) in the yaml metadata files which referred to the older sld format pointers in the file, and are not used in format 7 (sldy). These numbers anyway were read in as Integer and that generated an exception. I have tracked down several and changed them to Long. I have also added try/catch around the decoding of numbers from the yaml file, and that will produce warnings but will not kill the file load. If during testing you get any warnings in the console, please send them to me.

**Comment by melissalinkert** [comment]
> There were some large numbers (> 2^31) in the yaml metadata files which referred to the older sld format pointers in the file, and are not used in format 7 (sldy). These numbers anyway were read in as Integer and that generated an exception. I have tracked down several and changed them to Long. I have also added try/catch around the decoding of numbers from the yaml file, and that will produce warnings but will not kill the file load. If during testing you get any warnings in the console, please send them to me.

Thanks @nicolapapp. I understand that is the intention of the first few commits here, but there are other changes (for example https://github.com/ome/bioformats/pull/4100/commits/0fd31bdc923f3a1b629ddcf725118e985ebb148b) that are not related to large number handling. Could you please either remove those other changes, or summarize what they are and let us know how we can test them?

**Comment by melissalinkert** [comment]
Closing as noted above. @nicolapapp, feel free to re-open this pull request once the extra commits are removed, or the full set of changes is described along with appropriate test data.

**Pull request closed without merging**
