### PR TITLE
Java 17 support

### LINKED ISSUE #3659: Illegal reflective access by kryo
I'm not sure where I should report this issue, so please feel free to tell me if it should go somewhere else.

I'm running QuPath, and am opening lots of images using the BioFormats library to create thumbnail images.  On one image, I get the following warning:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.esotericsoftware.kryo.serializers.FieldSerializer (file:/home/jdg/qupath/build/dist/QuPath-0.2.3/lib/app/kryo-2.24.0.jar) to field java.util.regex.Pattern.pattern
WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.kryo.serializers.FieldSerializer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

The only use of the kryo library in QuPath is as a dependency of BioFormats.  I had a look at the kryo GitHub page, and it's currently on version 6.0.1 or so; version 2.4.0 was released in 2014.  So if it's a bug in kryo, it may well have been fixed by now.

I am happy to share my code, in case that helps. Unfortunately, though, this issue also seems to be transient: I repeated the extraction and did not get any warnings the second time around.  But my colleague, using the same code, is also sporadically getting this same warning.

### PR DESCRIPTION
**Pull request by sbesson**
Fixes #3659 

Java 17 LTS was released in September 2021 and in getting increasing used in the community by consumers of Bio-Formats e.g. `bioformats2raw` or `QuPath`. While there has been few reports so far indicating, this PR aims to bring full Java 17 support to Bio-Formats in the upcoming minor release, adding the required testing infrastructure and making the minimal set of code changes.

Summary of changes:

- [7ef4d15](https://github.com/ome/bioformats/pull/3815/commits/7ef4d1522ba719c4e24f851dc84cab32b34d1c52) and [f6d9c4b](https://github.com/ome/bioformats/pull/3815/commits/f6d9c4bcda975178bcece9fe19c7f73ba3c0dea7) add Java 17 to the GitHub Actions testing matrix 
- [6bf30d7](https://github.com/ome/bioformats/pull/3815/commits/6bf30d7be1e0de8edfe4a8a620f1a9bd6daace80) and [bf047fb](https://github.com/ome/bioformats/pull/3815/commits/bf047fbb3204db221a089fd62e148b9d8f163ff1) make the minimal changes to the `test-suite` infrastructure to have the automated tests running against JDK 17
- [d27a825](https://github.com/ome/bioformats/pull/3815/commits/d27a82539749c0edc006ecb4876778057e8c4a78), [767733f](https://github.com/ome/bioformats/pull/3815/commits/767733f35c8c8769a9466b732db6ede1681870d6), [43b572f](https://github.com/ome/bioformats/pull/3815/commits/43b572f22fda1e923fbb9fff3220d7c98f53a49a), [a315e5b](https://github.com/ome/bioformats/pull/3815/commits/a315e5bc07bb8e1e98058b8fc122c623606a912b) and [7769fa8](https://github.com/ome/bioformats/pull/3815/commits/7769fa8dee3bad5b81f10102ac987c32ea27a5e6) contain the minimal reader changes required for the memoization on Java 17
-  [07b8507](https://github.com/ome/bioformats/pull/3815/commits/07b85072d482d459fc9ad28eae20e44e2d0e8bc4) upgrades `ome-codecs` to `0.4.2` which includes the required upgrade of `io.airlit.aircompressor` to version 0.21. As demonstrated in the discussion of this PR, this change required https://github.com/ome/bioformats/pull/3923 to fix the Ant build

Related work:

- https://github.com/ome/bioformats/pull/3796 also fixes an issue exposed when using Java 17
- https://github.com/ome/devspace/pull/194 proposes to add the infrastructure to alternate between JDK versions in the daily Bio-Formats CI coverage and https://github.com/ome/devspace/pull/196 adds JDK 17 to the rotation (currently used in `merge-ci.openmicroscopy.org)

### CODE REVIEW

**Comment by dgault** [comment]
The `ome-poi` bump to 5.3.5 has been removed as develop has now been bumped to 5.3.6

On a separate note, when running the test suite you will run into issues with the file leak detector using Java 17:
https://github.com/jenkinsci/lib-file-leak-detector/issues/86

**Comment by sbesson** [comment]
> On a separate note, when running the test suite you will run into issues with the file leak detector using Java 17:
https://github.com/jenkinsci/lib-file-leak-detector/issues/86

Thanks for cross-linking to this issue which was definitely on my radar. The upgrade of file-leak-detector to 1.15 was necessary in order to get the test-suite simply running under Java 17. As per the nature of the changes, some of the logic might possibly have been disabled. On the other hand, file leak detection should at least be remain on Java 8 and Java 11 (as #3828 should demonstrated).

Also using the occasion to capture the progress on this investigation, with the set of changes above, the tests were executed once against the curated QA repository under Java 17 - see https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-test-repo/1154 for the build logs. The run was overall successful and only failed on 6 folders. These will need closer examination and I expect changes similar to #3796 will be required.

**Comment by sbesson** [comment]
Testing the memo file generation on JDK 17 with one of the failing samples points at the serialization of `loci.common.Location` private field as a source of issue

```
failed to save memo file: /tmp/cache/uod/idr/repos/curated/ome-tiff/pam/SingleImage-09242010-1031-049/.SingleImage-09242010-1031-049.xml.bfmemo
com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Unable to create serializer "com.esotericsoftware.kryo.serializers.FieldSerializer" for class: java.io.File
Serialization trace:
file (loci.common.Location)
cfgFile (loci.formats.in.PrairieReader)
readers (loci.formats.ImageReader)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:101)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:361)
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:302)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:557)
	at loci.formats.Memoizer$KryoDeser.saveReader(Memoizer.java:206)
	at loci.formats.Memoizer.saveMemo(Memoizer.java:968)
	at loci.formats.Memoizer.setId(Memoizer.java:697)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:662)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1035)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1121)
Caused by: java.lang.IllegalArgumentException: Unable to create serializer "com.esotericsoftware.kryo.serializers.FieldSerializer" for class: java.io.File
	at com.esotericsoftware.kryo.factories.ReflectionSerializerFactory.makeSerializer(ReflectionSerializerFactory.java:65)
	at com.esotericsoftware.kryo.factories.ReflectionSerializerFactory.makeSerializer(ReflectionSerializerFactory.java:43)
	at com.esotericsoftware.kryo.Kryo.newDefaultSerializer(Kryo.java:396)
	at com.esotericsoftware.kryo.Kryo.getDefaultSerializer(Kryo.java:380)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.registerImplicit(DefaultClassResolver.java:74)
	at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:508)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:97)
	at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:540)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:75)
	... 17 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedConstructorAccessor1.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.esotericsoftware.kryo.factories.ReflectionSerializerFactory.makeSerializer(ReflectionSerializerFactory.java:51)
	... 25 common frames omitted
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @6b06aa9b
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.buildValidFields(FieldSerializer.java:283)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.rebuildCachedFields(FieldSerializer.java:216)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.rebuildCachedFields(FieldSerializer.java:157)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.<init>(FieldSerializer.java:150)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.<init>(FieldSerializer.java:134)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.<init>(FieldSerializer.java:130)
	... 30 common frames omitted
```

From a quick review of https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-test-repo/1154, several of the formats which failed the tests (`cv7000`, `cellvoyager`, `prairie`, `volocity`) include a `Location` private field

```
(base) sbesson@Sebastiens-MacBook-Pro bioformats % git grep "private.*Location .*;"
components/formats-bsd/src/loci/formats/Memoizer.java:  private Location realFile;
components/formats-bsd/src/loci/formats/tools/FakeImage.java:  private Location directoryRoot;
components/formats-gpl/src/loci/formats/in/CV7000Reader.java:  private Location parent;
components/formats-gpl/src/loci/formats/in/CellVoyagerReader.java:  private Location measurementFolder;
components/formats-gpl/src/loci/formats/in/CellVoyagerReader.java:  private Location imageFolder;
components/formats-gpl/src/loci/formats/in/CellVoyagerReader.java:  private Location measurementResultFile;
components/formats-gpl/src/loci/formats/in/CellVoyagerReader.java:  private Location omeMeasurementFile;
components/formats-gpl/src/loci/formats/in/PrairieReader.java:  private Location xmlFile, cfgFile, envFile;
components/formats-gpl/src/loci/formats/in/VolocityReader.java:  private Location dir = null;
```

**Comment by melissalinkert** [comment]
https://github.com/EsotericSoftware/kryo/issues/859#issuecomment-1011652452 is maybe related. One approach is to switch the `Location` fields to just `String`. https://github.com/melissalinkert/bioformats/commits/java_17 has commits to do this, which seems to fix everything except `ome-tiff` and `zeiss-czi`.

**Comment by sbesson** [comment]
That's great. Do you want to add these commits to this branch so that we can get them testing in JDK 8/11 before re-enabling JDK17?

I think the errors in `ome-tiff` were caused by filesets read by `PrairieReader` so I am optimistic your changes will address these as well.

For `zeiss-czi`, a quick test shows the underlying exception is

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.airlift.compress.zstd.ZstdFrameDecompressor.verifyMagic(ZstdFrameDecompressor.java:952)
	at io.airlift.compress.zstd.ZstdFrameDecompressor.getDecompressedSize(ZstdFrameDecompressor.java:944)
	at io.airlift.compress.zstd.ZstdDecompressor.getDecompressedSize(ZstdDecompressor.java:96)
	at loci.formats.in.ZeissCZIReader$SubBlock.readPixelData(ZeissCZIReader.java:4101)
	at loci.formats.in.ZeissCZIReader$SubBlock.readPixelData(ZeissCZIReader.java:4017)
	at loci.formats.in.ZeissCZIReader$SubBlock.readPixelData(ZeissCZIReader.java:4012)
	at loci.formats.in.ZeissCZIReader.initFile(ZeissCZIReader.java:773)
	at loci.formats.FormatReader.setId(FormatReader.java:1473)
	at loci.formats.ImageReader.setId(ImageReader.java:861)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:662)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1035)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1121)
Caused by: io.airlift.compress.IncompatibleJvmException: Zstandard requires access to java.nio.Buffer raw address field
	at io.airlift.compress.zstd.UnsafeUtil.<clinit>(UnsafeUtil.java:53)
	... 12 more
```

which comes down to the `io.airlift.aircompressor` dependency.

**Comment by sbesson** [comment]
[fb60d7c](https://github.com/ome/bioformats/pull/3815/commits/fb60d7c1ac01dfdae2b2b7cda9f84bb0c1a8d8fa) reverts the `aircompressor` dependency bump. While the new dependency compiled without issue with the Maven build system, this failed the Ant builds while retrieving dependencies

```
 [artifact:dependencies] Downloading: io/airlift/aircompressor/0.21/aircompressor-0.21.pom from repository central at https://repo.maven.apache.org/maven2
[artifact:dependencies] Transferring 6K from central
[artifact:dependencies] Downloading: io/airlift/airbase/112/airbase-112.pom from repository central at https://repo.maven.apache.org/maven2
[artifact:dependencies] Transferring 67K from central
[artifact:dependencies] Downloading: org/junit/junit-bom/5.8.0-M1/junit-bom-5.8.0-M1.pom from repository central at http://repo1.maven.org/maven2
``` 

Shortly, the issue is that the Ant build is using the [maven-ant-tasks](https://maven.apache.org/ant-tasks/) project to resolve dependencies. The goal of this change was to reduce the need for the dependencies to be declared twice and have both Ant and Maven using the POM file as the single source of truth. Unfortunately, this component is now retired, unsupported and internally uses the hardcoded HTTP version of the Central repository (which has now been updated to HTTPS - https://links.sonatype.com/central/501-https-required) to resolve parent POMs.


A couple of options from a quick brainstorming with @melissalinkert, rouhgly listed in order ranging from the minimal cost+value to the maximal cost+value:

- edit the XML file and package a custom version of the JAR as mentioned in https://stackoverflow.com/questions/59948747/maven-ant-task-transitive-pom-dependencies-and-https-issue
- migrate from maven-ant-tasks to the recommended [maven artifact resolver](https://maven.apache.org/resolver-ant-tasks/) alternative
- remove the dual build system: drop Ant fully in favor of Maven or Gradle

Immediately, [fb60d7c](https://github.com/ome/bioformats/pull/3815/commits/fb60d7c1ac01dfdae2b2b7cda9f84bb0c1a8d8fa) will allow us to test the other fixes  and start considering options for the `aircompressor` dependency upgrade.

**Comment by joshmoore** [comment]
> [EsotericSoftware/kryo#859 (comment)](https://github.com/EsotericSoftware/kryo/issues/859#issuecomment-1011652452) is maybe related. One approach is to switch the `Location` fields to just `String`.

For for chiming in late, but just wanted to add that I assume since Location is in our code we could provide a serializer for it to not need to switch to `String`s.

But in general, this incompatibility between Java internals and Kryo doesn't fill me with fuzzies.

**Comment by dgault** [comment]
ome-codecs with the updated aircompressor has now been released and should be available to bump to https://github.com/ome/ome-codecs/releases/tag/v0.4.2

**Comment by sbesson** [comment]
Unfortunately upgrading `ome-codecs` to 0.4.2 brings us back to the build system issue previously raised in https://github.com/ome/bioformats/pull/3815#issuecomment-1156641573. Unlike at the time of the previous comment, we now have a set of commits allowing to have all repository tests passing on JDK 8, 11 17.  I'll evaluate the three options discussed previously and discuss them at an upcoming Formats meeting.

**Comment by sbesson** [comment]
With the inclusion of https://github.com/ome/bioformats/pull/3923, the Ant workflow can now be reactivated and Java 17 also added to the matrix. The CI builds have been passing consistently for the last few week with the repository tests being executed successfully on JDK 8, JDK 11, JDK 17. The latest state of this branch obviously needs to be re-evaluated but assuming no regression, there is nothing else coming from my side on this front.
The description has been updated to reflect more precisely the latest state of the proposed changes and these code changes are now ready for review and hopefully inclusion in the upcoming 6.12.0 release of Bio-Formats

**Review by melissalinkert — APPROVED** [review]

**Review by dgault — APPROVED** [review]
All builds and tests have been stable with this PR included for a while now. Getting this merged for inclusion with the 6.12.0 release

**Pull request merged**
